// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tttmovpriooyxekcgrhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0dG1vdnByaW9veXhla2Nncmh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTg1MzUsImV4cCI6MjA2MTA3NDUzNX0.ZcIJ_V_OEdeN1z0QVnsZX2XRLAvhy0NEbF4WUCO6M7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);